version: 0.0.{build}
branches:
  only:
  - master
  - testBuild
init:
- cmd: >-
    echo git has tag: %APPVEYOR_REPO_TAG%

    echo git tag number: %APPVEYOR_REPO_TAG_NAME%

    if /I "%APPVEYOR_REPO_TAG%"=="true" (

    appveyor UpdateBuild -Version "APPVEYOR_REPO_TAG_NAME"

    )
build:
  verbosity: minimal
test:
  assemblies: '*.UnitTest'