version: 0.0.{build}
branches:
  only:
  - master
  - testBuild
init:
- ps: >-
    "git has tag updated" + $env:APPVEYOR_REPO_TAG

    "git tag name" + $env:APPVEYOR_REPO_TAG_NAME


    if($env:APPVEYOR_REPO_TAG -eq 'true'){
    	"Update Version Number"
        "$env:APPVEYOR_REPO_TAG_NAME" + "." + "$env:APPVEYOR_BUILD_NUMBER"
    	Update-AppveyorBuild -Version "$env:APPVEYOR_REPO_TAG_NAME" + ".{build}"
    }
    "Updated status"
build:
  verbosity: minimal
test:
  assemblies: '**\*.*Test.dll'
before_build:
  - nuget restore src\CommandLineApplicationLauncher.sln